name: GitHub Actions Basics

on:
  push:

jobs:
  Basics:
    runs-on: ubuntu-latest

    steps:
      - name: Chechout Repository
        uses: actions/checkout@v4

      - name: Print Current Directory 
        run: pwd

      - name: List Files
        run: ls -la

      - name: Display Current User
        run: whoami

      - name: Display date
        run: date

      - name: Create File
        run: echo "Hello GitHub Actions" > message.txt

      - name: Read File
        run: cat message.txt

      - name: Multiple Commands
        run: | 
          echo "Workflow Finished"
          pwd
          ls
