name: My First Workflow

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Chechout Repository
        run: actions/checkout@v4

      - name: Print Current Directory 
        run: pwd

      - name: List Files
        run: ls -la

      - name: Display Current User
        run: whoami

      - name: Display date
        run: date
